export let ELEMENT_DATA= [
    {
      orderNumber: 30226, nop: 1, recruiter: 'Prem', pbDate: '4/8/2022', stratification: 'Designer Consultant',
      targetRate: 100, skillGroup: 'Agile Coach', primarySkill: 'Agile Coach',
      skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
      jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. Agile Coach will work with multiple teams with varying levels of agile maturity. He/She should be able to coach the product teams to adapt agile principles and practices. Continuously improve and promote agile values and principles in a globally distributed development teams. The Agile Coach will work daily with Product Owner, Product Manager, development team as well as Senior Leaders and other stake holders responsible for agile adoption and execution",
      positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '0%', submittedAboveTarget: '', region: 'EU', lineOfBusiness: 'Ford Blue', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
      ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
      positionOpenMonth: 'Apr, 2022', status: 'opened'
    },
  
    // {
    //   orderNumber: 30520, nop: 1, recruiter: 'Not-Sourcing', pbDate: '6/9/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Team Center', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'New', didCustomerReachOut: 'Yes', probability: '45%', submittedAboveTarget: '', region: 'EU', lineOfBusiness: 'Ford Next', productLine: 'OTA - Build', ll6: 'Venu Renganathan',
    //   ll5: 'Meenakshi Dhandapani', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Jun,2022', status: 'closed'
    // },
  
    // {
    //   orderNumber: 30592, nop: 1, recruiter: 'Praveen', pbDate: '10/7/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'J2EE', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus ",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. Agile Coach will work with multiple teams with varying levels of agile maturity. He/She should be able to coach the product teams to adapt agile principles and practices. Continuously improve and promote agile values and principles in a globally distributed development teams. The Agile Coach will work daily with Product Owner, Product Manager, development team as well as Senior Leaders and other stake holders responsible for agile adoption and execution",
    //   positionType: 'Back Fill', didCustomerReachOut: 'Yes', probability: '70%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: 'GIVIS/GVMS', ll6: 'Venu Renganathan',
    //   ll5: 'Amy Palazz', ll4: 'Jeff Koons', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Oct,2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 30592, nop: 1, recruiter: 'Vinod', pbDate: '6/20/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'SAP', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '80%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Model E', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Jun,2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 30226, nop: 1, recruiter: 'Prem', pbDate: '4/8/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Agile Coach', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '0%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Apr, 2022', status: 'closed'
    // },
    // {
    //   orderNumber: 30226, nop: 1, recruiter: 'Prem', pbDate: '4/8/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Agile Coach', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. Agile Coach will work with multiple teams with varying levels of agile maturity. He/She should be able to coach the product teams to adapt agile principles and practices. Continuously improve and promote agile values and principles in a globally distributed development teams. The Agile Coach will work daily with Product Owner, Product Manager, development team as well as Senior Leaders and other stake holders responsible for agile adoption and execution",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '0%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Apr, 2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 30520, nop: 1, recruiter: 'Not-Sourcing', pbDate: '6/9/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Team Center', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'New', didCustomerReachOut: 'Yes', probability: '45%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Next', productLine: 'OTA - Build', ll6: 'Venu Renganathan',
    //   ll5: 'Meenakshi Dhandapani', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Jun,2022', status: 'closed'
    // },
  
    // {
    //   orderNumber: 30572, nop: 1, recruiter: 'Praveen', pbDate: '10/7/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'J2EE', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus ",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. Agile Coach will work with multiple teams with varying levels of agile maturity. He/She should be able to coach the product teams to adapt agile principles and practices. Continuously improve and promote agile values and principles in a globally distributed development teams. The Agile Coach will work daily with Product Owner, Product Manager, development team as well as Senior Leaders and other stake holders responsible for agile adoption and execution",
    //   positionType: 'Back Fill', didCustomerReachOut: 'Yes', probability: '70%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: 'GIVIS/GVMS', ll6: 'Venu Renganathan',
    //   ll5: 'Amy Palazz', ll4: 'Jeff Koons', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Oct,2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 30593, nop: 1, recruiter: 'Vinod', pbDate: '6/20/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'SAP', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '80%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Model E', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Jun,2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 30326, nop: 1, recruiter: 'Prem', pbDate: '4/8/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Agile Coach', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '0%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Apr, 2022', status: 'closed'
    // },
  
    // {
    //   orderNumber: 31520, nop: 1, recruiter: 'Not-Sourcing', pbDate: '6/9/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'Team Center', primarySkill: 'Agile Coach',
    //   skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. . In depth knowledge of how Scrum, Kanban and Scaling agile models . Experience coaching and training individuals and teams in agile principles and practices. . Should have worked as Scrum Master or RTE or Product Owner or Agile Coach in the past. . Provide hands on coaching to 2-4 Agile teams simultaneously with in-depth guidance on agile roles, rituals, and artifacts. . Mentor participants in all Agile roles-especially the ones of scrum master and product owner . Continuously measure and report the progress of teams and Business units in meeting their goals. . Align local efforts to Enterprise level Agility goals . Conduct occasional classroom training sessions on variety of Agile related topics. . Agile Lifecycle Management tool expertise.preferably with Rally software . Be an active, involved member of FORD Transformation Office - Enterprise Agility Coaching team . Either possesses a background working directly in a technology role or can demonstrate the ability to understand the procedures and challenges of a variety of technology functions involved in the product development life cycle. . Flexible and resilient; willingness to take initiative to create approaches to complex problems. . Ability to thrive in an environment with a high-degree of change. . Strong collaborative problem solver . Exposure to XP engineering practices such as TDD , BDD , CI/ CD, Automation etc is a plus ",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'New', didCustomerReachOut: 'Yes', probability: '45%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Next', productLine: 'OTA - Build', ll6: 'Venu Renganathan',
    //   ll5: 'Meenakshi Dhandapani', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: 'Jun, 2022', status: 'opened'
    // },
  
    // {
    //   orderNumber: 32592, nop: 1, recruiter: 'Praveen', pbDate: '10/7/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'J2EE', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. ",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Back Fill', didCustomerReachOut: 'Yes', probability: '70%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Ford Blue', productLine: 'GIVIS/GVMS', ll6: 'Venu Renganathan',
    //   ll5: 'Amy Palazz', ll4: 'Jeff Koons', ll3: 'Aaron Rajda',
    //   positionOpenMonth: '10-2022', status: 'closed'
    // },
  
    // {
    //   orderNumber: 39592, nop: 1, recruiter: 'Vinod', pbDate: '6/20/2022', stratification: 'Designer Consultant',
    //   targetRate: 100, skillGroup: 'SAP', primarySkill: 'Agile Coach', skillset: "Expertise in Agile and Lean ways of working at project/ enterprise level. ",
    //   jobDescription: "More than 8+ years of progressive responsibilities in IT companies with minimum 3+ years of experience in Agile Projects. ",
    //   positionType: 'Dont know', didCustomerReachOut: 'Yes', probability: '80%', submittedAboveTarget: '', region: 'NA', lineOfBusiness: 'Model E', productLine: '0', ll6: 'Ravikiran Manchi Saraf',
    //   ll5: 'Amy Palazz', ll4: 'Aaron Rajda', ll3: 'Aaron Rajda',
    //   positionOpenMonth: '06-2022', status: 'opened'
    // },
  
  ];
